function p = getpermlist

% Pre-processing options
p.proc.despike = struct( ...
    'none', struct('skip', true), ...
    'despike', struct('skip', false) ...
    );
p.proc.slice = struct( ...
    'none', struct('skip', true), ...
    'slice', struct('skip', false) ...
    );
p.proc.realign = struct( ...
    'realign', struct('unwarp', false));%, ...
%     'unwarp', struct('unwarp', true) ...
%     );
p.proc.coregister = struct( ...
    'def', struct() ...
    );
p.proc.segment = struct( ...
    'def', struct() ...
    );
p.proc.normmodorder = struct( ...
    'normfirst', struct('first', 'normfirst'), ...
    'modfirst', struct('first', 'modfirst') ...
    );
p.proc.norm = struct( ...
    'func', struct('normtype', 'func'), ...
    'anat', struct('normtype', 'anat'), ...
    'seg', struct('normtype', 'seg') ...
    );
p.proc.smooth = struct( ...
    'fwhm4', struct('opts', struct('fwhm', [4 4 4])), ...
    'fwhm8', struct('opts', struct('fwhm', [8 8 8])), ...
    'fwhm12', struct('opts', struct('fwhm', [12 12 12])) ...
    );

% Modeling options
p.model.hpf = struct( ...
    'none', struct('hpf', -inf), ...
    'hpf128', struct('hpf', 128) ...
    );
p.model.cvi = struct( ...
    'none', struct('cvi', 'none'), ...
    'ar1', struct('cvi', 'AR(1)') ...
    );
p.model.catruns = struct( ...
    'none', struct('catruns', false), ...
    'catruns', struct('catruns', true) ...
    );
p.model.basis = struct( ...
    'fir', struct( ...
        'basis', 'fir', ...
        'length', 16 ...
        ), ...
    'hrf', struct( ...
        'basis', 'hrf', ...
        'derivs', 'none' ...
        ) ...
    );
p.model.rpreg = struct( ...
    'none', struct('rpreg', false, 'rppow', 1, 'rpspin', 0), ...
    'rp6', struct('rpreg', true, 'rppow', 1, 'rpspin', 0), ...
    'rp12', struct('rpreg', true, 'rppow', 1, 'rpspin', 1), ...
    'rp24', struct('rpreg', true, 'rppow', 2, 'rpspin', 1) ...
    );
